spring.application.name=spring-ai-vs-langgraph4j
#spring.ai.openai.api-key=${OPENAI_API_KEY:mock-key-for-local-testing}
#spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:7b